name: Remote Terraform Apply

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure infra directory exists on EC2 instance
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }} '
            if [ ! -d ~/infra ]; then
              echo "Creating infra directory..."
              mkdir ~/infra
            else
              echo "Infra directory already exists. No action taken."
            fi
          '

      - name: Copy infra folder to EC2 instance
        run: |
          # Check if the infra directory exists in the GitHub Actions runner
          if [ -d infra ]; then
            scp -i ~/.ssh/deploy_key -r infra/* ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }}:~/infra
          else
            echo "Error: infra directory does not exist in the repository."
            exit 1
          fi

      - name: Run Terraform Commands on EC2 instance
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }} '
            cd ~/infra
            terraform init
            terraform apply -auto-approve
          '
