name: Remote Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev/prod)"
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure infra and application directories exist on EC2 instance
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }} '
            for dir in ~/infra ~/application; do
              if [ ! -d "$dir" ]; then
                echo "Creating directory: $dir"
                mkdir "$dir"
              else
                echo "Directory already exists: $dir"
              fi
            done
          '

      - name: Copy infra and app folders to EC2 instance
        run: |
          # Check if the infra directory exists in the GitHub Actions runner
          if [ -d infra ]; then
            scp -i ~/.ssh/deploy_key -r infra/* ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }}:~/infra
          else
            echo "Error: infra directory does not exist in the repository."
            exit 1
          fi

          if [ -d application ]; then
            scp -i ~/.ssh/deploy_key -r application/* ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }}:~/application
          else
            echo "Error: application directory does not exist in the repository."
            exit 1
          fi

      - name: Run Terraform Commands on EC2 instance
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }} '
            cd ~/infra/environments/${{ github.event.inputs.environment }}
            terraform init
            terraform apply -auto-approve
          '
