name: Remote Terraform Apply
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Execute Terraform Commands
        run: |
          BRANCH=${{ github.event.inputs.branch }}

          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }} '
            if [ -d ~/deployment ]; then
              echo "Directory exists, pulling latest changes from branch $BRANCH..."
              cd ~/deployment
              git fetch origin
              git checkout $BRANCH
              git pull origin $BRANCH
            else
              echo "Directory does not exist, cloning repository from branch $BRANCH..."
              git clone --branch $BRANCH ${{ github.server_url }}/${{ github.repository }} ~/deployment
            fi
            
            # Navigate to infrastructure directory and run terraform commands
            cd ~/deployment/infra
            
            # Initialize and apply
            terraform init
            terraform apply -auto-approve
          '
