name: Remote Terraform Apply

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Check for and remove existing infra folder on EC2 instance
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }} '
            if [ -d ~/infra ]; then
              echo "Existing infra folder found. Deleting..."
              rm -rf ~/infra
            else
              echo "No existing infra folder found. Proceeding with deployment."
            fi
          '

      - name: Copy infra folder to EC2 instance
        run: |
          scp -i ~/.ssh/deploy_key -r infra ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }}:/home/${{ secrets.SSH_USER }}/

      - name: Run Terraform Commands on EC2 instance
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }} '
            cd ~/infra
            terraform init
            terraform apply -auto-approve
          '
