name: Remote Terraform Destroy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev/prod)"
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Execute Terraform Commands
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.AWS_HOST }} '

          # Navigate to infrastructure directory and run terraform commands
            cd ~/infra/environments/${{ github.event.inputs.environment }}
            terraform init
            terraform destroy -auto-approve
          '
