name: Terraform Code Checks

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev/prod)"
        required: true
        type: choice
        options:
          - dev
          - prod

permissions: read-all

jobs:
  tflint-checks:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Check out Git Repository
        uses: actions/checkout@v3

      # Cache TFLint plugins
      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      # Setup TFLint
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          github_token: ${{ secrets.CI_GITHUB_TOKEN }}

      # Print TFLint version
      - name: Show version
        run: tflint --version

      # Install TFLint plugins
      - name: Init TFLint
        run: tflint --init

      # Run TFLint
      - name: Run TFLint
        run: tflint -f compact --recursive || true

  tfsec-checks:
    needs: tflint-checks
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Check out Git Repository
        uses: actions/checkout@v2

      # Run Tfsec
      - name: Run Tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
